// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeeSharpCarCare.Core.Data;

#nullable disable

namespace SeeSharpCarCare.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("VIN");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("RepairCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.RepairCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RepairName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RepairCodes");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.TechnicianWorkOrder", b =>
                {
                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("TechnicianId", "WorkOrderId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("TechnicianWorkOrder");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("VIN");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TechnicianWorkOrderTechnicianId")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicianWorkOrderWorkOrderId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasFilter("[InvoiceId] IS NOT NULL");

                    b.HasIndex("VIN");

                    b.HasIndex("TechnicianWorkOrderTechnicianId", "TechnicianWorkOrderWorkOrderId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Invoice", b =>
                {
                    b.HasOne("SeeSharpCarCare.Core.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeeSharpCarCare.Core.Models.Technician", null)
                        .WithMany("Invoices")
                        .HasForeignKey("TechnicianId");

                    b.HasOne("SeeSharpCarCare.Core.Models.Vehicle", "Vehicle")
                        .WithMany("Invoices")
                        .HasForeignKey("VIN")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Repair", b =>
                {
                    b.HasOne("SeeSharpCarCare.Core.Models.Invoice", null)
                        .WithMany("Repairs")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("SeeSharpCarCare.Core.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId");

                    b.HasOne("SeeSharpCarCare.Core.Models.WorkOrder", "WorkOrder")
                        .WithMany("Repairs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.TechnicianWorkOrder", b =>
                {
                    b.HasOne("SeeSharpCarCare.Core.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeeSharpCarCare.Core.Models.WorkOrder", "WokOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");

                    b.Navigation("WokOrder");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.WorkOrder", b =>
                {
                    b.HasOne("SeeSharpCarCare.Core.Models.Customer", "Customer")
                        .WithMany("WordkOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeeSharpCarCare.Core.Models.Invoice", "Invoice")
                        .WithOne("WorkOrder")
                        .HasForeignKey("SeeSharpCarCare.Core.Models.WorkOrder", "InvoiceId");

                    b.HasOne("SeeSharpCarCare.Core.Models.Vehicle", "Vehicle")
                        .WithMany("WorkOrders")
                        .HasForeignKey("VIN")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeeSharpCarCare.Core.Models.TechnicianWorkOrder", null)
                        .WithMany("WorkOrders")
                        .HasForeignKey("TechnicianWorkOrderTechnicianId", "TechnicianWorkOrderWorkOrderId");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("WordkOrders");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Invoice", b =>
                {
                    b.Navigation("Repairs");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Technician", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.TechnicianWorkOrder", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.Vehicle", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("SeeSharpCarCare.Core.Models.WorkOrder", b =>
                {
                    b.Navigation("Repairs");
                });
#pragma warning restore 612, 618
        }
    }
}
