// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeeSharpCarCare.API.Data;

#nullable disable

namespace SeeSharpCarCare.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RepairDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("VIN");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("RepairCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.RepairCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RepairName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RepairCodes");

                    b.HasData(
                        new
                        {
                            Id = "AC",
                            RepairName = "Air Conditioning"
                        },
                        new
                        {
                            Id = "BB",
                            RepairName = "Brake Bleeding"
                        },
                        new
                        {
                            Id = "BP",
                            RepairName = "Brake Pads"
                        },
                        new
                        {
                            Id = "BT",
                            RepairName = "Battery Testing"
                        },
                        new
                        {
                            Id = "BR",
                            RepairName = "Battery Replacement"
                        },
                        new
                        {
                            Id = "CL",
                            RepairName = "Clutch"
                        },
                        new
                        {
                            Id = "CR",
                            RepairName = "Coolant Flush"
                        },
                        new
                        {
                            Id = "CS",
                            RepairName = "Charging System"
                        },
                        new
                        {
                            Id = "CW",
                            RepairName = "Car Wash"
                        },
                        new
                        {
                            Id = "ECM",
                            RepairName = "Engine Control Module"
                        },
                        new
                        {
                            Id = "ES",
                            RepairName = "Engine Swap"
                        },
                        new
                        {
                            Id = "EM",
                            RepairName = "Electric Motor"
                        },
                        new
                        {
                            Id = "FP",
                            RepairName = "Fuel Pump"
                        },
                        new
                        {
                            Id = "HB",
                            RepairName = "Hybrid System"
                        },
                        new
                        {
                            Id = "HR",
                            RepairName = "Head Lights"
                        },
                        new
                        {
                            Id = "OC",
                            RepairName = "Oil Change"
                        },
                        new
                        {
                            Id = "SP",
                            RepairName = "Spark Plugs"
                        },
                        new
                        {
                            Id = "SS",
                            RepairName = "Suspension System"
                        },
                        new
                        {
                            Id = "ST",
                            RepairName = "Steering System"
                        },
                        new
                        {
                            Id = "TF",
                            RepairName = "Transmission Fluid"
                        },
                        new
                        {
                            Id = "TR",
                            RepairName = "Tire Rotation"
                        },
                        new
                        {
                            Id = "TRN",
                            RepairName = "Tire Replacement (New)"
                        },
                        new
                        {
                            Id = "TRU",
                            RepairName = "Tire Replacement (Used)"
                        },
                        new
                        {
                            Id = "TS",
                            RepairName = "Transmission Service"
                        },
                        new
                        {
                            Id = "WA",
                            RepairName = "Wheel Alignment"
                        },
                        new
                        {
                            Id = "WB",
                            RepairName = "Wheel Balancing"
                        });
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.TechnicianWorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("TechnicianWorkOrders");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("VIN");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RepairDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasFilter("[InvoiceId] IS NOT NULL");

                    b.HasIndex("VIN");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Invoice", b =>
                {
                    b.HasOne("SeeSharpCarCare.API.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeeSharpCarCare.API.Models.Technician", null)
                        .WithMany("Invoices")
                        .HasForeignKey("TechnicianId");

                    b.HasOne("SeeSharpCarCare.API.Models.Vehicle", "Vehicle")
                        .WithMany("Invoices")
                        .HasForeignKey("VIN")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Repair", b =>
                {
                    b.HasOne("SeeSharpCarCare.API.Models.Invoice", null)
                        .WithMany("Repairs")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("SeeSharpCarCare.API.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId");

                    b.HasOne("SeeSharpCarCare.API.Models.WorkOrder", "WorkOrder")
                        .WithMany("Repairs")
                        .HasForeignKey("WorkOrderId");

                    b.Navigation("Technician");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.TechnicianWorkOrder", b =>
                {
                    b.HasOne("SeeSharpCarCare.API.Models.Technician", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId");

                    b.HasOne("SeeSharpCarCare.API.Models.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.WorkOrder", b =>
                {
                    b.HasOne("SeeSharpCarCare.API.Models.Customer", "Customer")
                        .WithMany("WordkOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeeSharpCarCare.API.Models.Invoice", "Invoice")
                        .WithOne("WorkOrder")
                        .HasForeignKey("SeeSharpCarCare.API.Models.WorkOrder", "InvoiceId");

                    b.HasOne("SeeSharpCarCare.API.Models.Vehicle", "Vehicle")
                        .WithMany("WorkOrders")
                        .HasForeignKey("VIN")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Invoice");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("WordkOrders");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Invoice", b =>
                {
                    b.Navigation("Repairs");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Technician", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.Vehicle", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("SeeSharpCarCare.API.Models.WorkOrder", b =>
                {
                    b.Navigation("Repairs");
                });
#pragma warning restore 612, 618
        }
    }
}
